import { SpeechAnalyzer } from "@/utils/speechAnalyzer";

// const question = `Senator, we heard from Donald Trump this week that he wants to end all taxes on overtime pay for workers. How would this exemption work? Would this mean someone working a 40-hour work week would then not pay payroll taxes and not pay income taxes?`;
// const response = `Well, that's exactly how he envisions it. Of course, we're talking about hourly workers, and of course, when you work overtime in this country beyond 40 hours, you get time and a half, and the President saying, if you're one of those select hard workers that's really busting your rear end to try to make good in Kamala Harris's economy, then you should get a tax cut. And I think it fits fully, Margaret, with his entire tax agenda, which is, we want American workers to get tax cuts under President Trump's policies, and we want to actually penalize companies that are shipping jobs overseas through tariffs. And Kamala Harris's tax policies are, in fact, the inversion of that. She wants to raise taxes on American workers and actually reward companies for shipping jobs overseas. So, it is a really stark contrast between the agenda of Donald Trump and of Kamala Harris.`;
// const analysisResults = {
//   speakingPace: SpeechAnalyzer.speakingPace(response, 43),
//   gradeLevel: SpeechAnalyzer.gradeLevel(response),
//   topWords: SpeechAnalyzer.topNWords(response, 10),
//   fillerWords: SpeechAnalyzer.fillerWordCount(response),
//   structure: await SpeechAnalyzer.structure(question, response),
// };

// console.log(analysisResults);

// const response = `Well, almost by definition, Margaret, when you apply a tariff, what you're really doing is applying a penalty to somebody who manufactures or makes something overseas. You're basically charging them a penalty to bring it back into our country. And so, what we're trying to do here with these- these tariffs, is actually induce more people to make more things in the United States of America. One of the great tragedies of not just Kamala Harris's leadership, but 40 years of American failure, is that we've lost our critical manufacturing industries to Mexico, to China. We started to undo that for four years under Donald Trump's leadership, but we've got to do it for much longer and in a much more intense way, because, as we've learned just in the last few days, the world has gotten more dangerous. We can't rely on other people to make the stuff we need.`;
// const response = `Well, I think obviously Republicans believe American workers should keep more of their own money. And yes, I think that if we actually balance this out by penalizing some of these companies for manufacturing overseas, I do think that we can get this to balance out in the right way, Margaret, where we're not blowing a hole in the deficit, we're giving workers more their money. But to your point, we're actually making it easier to make things in the United States of America. Now you're exactly right. Sometimes it is a little bit cheaper to manufacture overseas, but we have to ask why that is. It's because a lot of these foreign countries use literal slave labor in manufacturing. We should not be allowing slave laborers to benefit from American markets. If you want access to our market, you've got to pay our workers fair wages. That is the Trump agenda, and it's something he already implemented once, by the way, Margaret, but is going to double down on in a second term.`;
const response = `Well, I think you have to take some recognition Margaret, that this is a negotiating tactic. You go into some of these negotiations, and sometimes you're going to have to do higher tariffs. Sometimes you might be able to do lower tariffs, but I don't think you go in saying you're going to do exactly this on every country, you use that as part of the negotiation. This is one thing that Donald Trump was so good at during his first term, is actually negotiating with foreign countries and benefiting American workers in the process. If you say you're not going to do any tariffs, you're basically going into these trade negotiations completely unilaterally disarmed. You don't want somebody who's negotiating for American workers, who's already saying, I'm not going to use the most important tool, which is exactly what Kamala Harris has done.`;
console.log(SpeechAnalyzer.gradeLevel(response));
